name: quizzo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http:
  buttons_tabbar:
  flutter_svg: ^2.2.0
  event_bus: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.9.3
  cached_network_image:
  dotted_line:
  provider: ^6.1.2
  get: ^4.6.6
  image_picker:
  url_launcher:
  google_fonts:
  shared_preferences: ^2.2.1
  flutter_otp_text_field: ^1.1.1
  flutter_spinkit: ^5.2.2
  table_calendar:
  intl: ^0.19.0
  supabase_flutter: ^2.10.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
