name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze --fatal-infos

      - name: Check for unused files
        run: |
          dart pub global activate dart_code_metrics
          dart pub global run dart_code_metrics:metrics check-unused-files lib

      - name: Run custom lint rules
        run: |
          dart pub global activate custom_lint
          dart pub global run custom_lint

      - name: Check for TODO/FIXME comments
        run: |
          echo "## TODO/FIXME Comments Found:" > lint_comments.txt
          grep -r "TODO\|FIXME" lib/ --exclude-dir={build,*.g.dart} || true

      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: lint_comments.txt
